#!/usr/bin/env python
import math as m
import numpy as np
import scipy as sp
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D 

eps = m.pow(10,-10)

def rLommel(mu, nu, b):
	t = (1/(mu + 1 + nu)) * (1/(mu + 1 - nu))
	r = t
	n = 2
	while m.fabs(t) > eps:
		print r
		t = t * ((-b) / (mu + 2*n - 1 - nu)) * (b / (mu + 2*n - 1 + nu)) 
		r = r + t
		n = n + 1
	return r

print eps
print rLommel(1.5, .1, 5)